# Generated by Django 4.0.4 on 2023-01-13 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_login_cv_alter_login_these'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='cv',
            field=models.FileField(upload_to='cvs/%y/%m/%d', verbose_name='cvs'),
        ),
        migrations.AlterField(
            model_name='login',
            name='these',
            field=models.FileField(upload_to='theses/%y/%m/%d', verbose_name='theses'),
        ),
    ]
