# Generated by Django 4.0.4 on 2023-01-17 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_login_cv_alter_login_these'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='Demande',
        ),
        migrations.RemoveField(
            model_name='male',
            name='girls',
        ),
        migrations.RemoveField(
            model_name='user',
            name='products',
        ),
        migrations.DeleteModel(
            name='Vedio',
        ),
        migrations.DeleteModel(
            name='Female',
        ),
        migrations.DeleteModel(
            name='Male',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
