# Generated by Django 4.0.4 on 2023-01-23 18:28

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_rename_login_demande_remove_male_girls_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DOTI', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('nom_prenom', models.CharField(max_length=255)),
                ('emailAcademic', models.CharField(max_length=50)),
                ('GRADE', models.CharField(max_length=50)),
                ('DEPARTEMENT', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='demande',
            old_name='cv',
            new_name='Cv',
        ),
        migrations.RenameField(
            model_name='demande',
            old_name='these',
            new_name='ThesePiece',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='password',
        ),
        migrations.AddField(
            model_name='demande',
            name='AvisSoutnance',
            field=models.ImageField(default='photos/22/11/24/cv.pdf', upload_to='photos/%y/%m/%d', verbose_name='photos'),
        ),
        migrations.AddField(
            model_name='demande',
            name='Created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='demande',
            name='DOTI',
            field=models.IntegerField(default=11111),
        ),
        migrations.AddField(
            model_name='demande',
            name='DateProposee',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='demande',
            name='Heure',
            field=models.CharField(choices=[('1', '9:00AM'), ('2', '9:30AM'), ('3', '10:00AM'), ('4', '10:30AM'), ('5', '11:00AM'), ('6', '11:30AM'), ('7', '12:00PM'), ('8', '12:30PM'), ('9', '1:00PM'), ('10', '1:30PM'), ('11', '2:00PM'), ('12', '2:30PM'), ('13', '3:00PM'), ('14', '3:30PM'), ('15', '4:00PM'), ('16', '4:30PM'), ('17', '5:00PM'), ('18', '5:30PM')], default='', max_length=255),
        ),
        migrations.AddField(
            model_name='demande',
            name='Jury',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='demande',
            name='Nom',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='demande',
            name='Phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Contact phone number', max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='demande',
            name='Prenom',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='demande',
            name='Tele',
            field=models.CharField(default='', max_length=255),
        ),
    ]
