# Generated by Django 4.0.4 on 2023-01-23 20:43

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_demande_avissoutnance_alter_demande_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='DateProposee',
            field=models.DateField(verbose_name='Date Propose'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='Phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='+212699999999', max_length=128, region=None),
        ),
    ]
