# Generated by Django 4.0.4 on 2023-01-23 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_alter_demande_dateproposee_alter_demande_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='Created',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='DateProposee',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='Heure',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='Jury',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='Phone',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='Tele',
        ),
    ]
