# Generated by Django 4.0.4 on 2023-01-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_demande_created_demande_heure_demande_jury_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='Tele',
            field=models.CharField(default='', max_length=255, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='Jury',
            field=models.TextField(default='', verbose_name='Jury NomPrenom || Etablissement || Role'),
        ),
    ]
