# Generated by Django 4.0.4 on 2023-01-24 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_demande_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professeur',
            old_name='nom_prenom',
            new_name='nomComplete',
        ),
        migrations.RemoveField(
            model_name='professeur',
            name='DEPARTEMENT',
        ),
        migrations.RemoveField(
            model_name='professeur',
            name='GRADE',
        ),
        migrations.RemoveField(
            model_name='professeur',
            name='emailAcademic',
        ),
        migrations.RemoveField(
            model_name='professeur',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='professeur',
            name='prenom',
        ),
    ]
