# Generated by Django 4.0.4 on 2023-01-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_demande_nomprenom'),
    ]

    operations = [
        migrations.AddField(
            model_name='professeur',
            name='DEPART',
            field=models.CharField(choices=[('1', 'Maths'), ('2', 'Physique'), ('3', 'Biologie'), ('4', 'Chimie'), ('5', 'Géologie'), ('6', 'Informatique'), ('7', 'LC')], default='----', max_length=255, verbose_name='DEPARTEMENT'),
        ),
        migrations.AddField(
            model_name='professeur',
            name='Grade',
            field=models.CharField(default='', max_length=255),
        ),
    ]
