# Generated by Django 4.0.4 on 2023-01-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_professeur_depart_professeur_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='Cv',
            field=models.FileField(default='cvs/22/11/24/cv.pdf', upload_to='cvs/%y/%m/%d', verbose_name='Cv'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='ThesePiece',
            field=models.FileField(default='theses/22/11/24/these.pdf', upload_to='theses/%y/%m/%d', verbose_name='These'),
        ),
    ]
