# Generated by Django 4.0.4 on 2023-01-24 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_alter_demande_cv_alter_demande_thesepiece'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='Doctorant',
            field=models.CharField(default='', max_length=255, verbose_name='Mr. Doctorant'),
        ),
    ]
