# Generated by Django 4.0.4 on 2023-02-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_remove_demandeced_nom_demandeced_doctorantapogee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeced',
            name='DateInscriptionThese',
            field=models.DateField(blank=True, null=True, verbose_name='date de 1ére inscription dans la thèse'),
        ),
        migrations.AddField(
            model_name='demandeced',
            name='DesciplineThese',
            field=models.CharField(default='', max_length=255, verbose_name='discipline de thèse '),
        ),
        migrations.AddField(
            model_name='demandeced',
            name='IntituleeThese',
            field=models.CharField(default='', max_length=255, verbose_name='intitulé de thèse'),
        ),
        migrations.AddField(
            model_name='demandeced',
            name='SpeciliteThses',
            field=models.CharField(default='', max_length=255, verbose_name='spécialité de thèse'),
        ),
        migrations.AddField(
            model_name='demandeced',
            name='TitreThese',
            field=models.CharField(default='', max_length=255, verbose_name='Titre de thèse'),
        ),
    ]
