# Generated by Django 4.0.4 on 2023-02-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_demandeced_dateinscriptionthese_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeced',
            name='Brevet',
            field=models.FileField(default='Brevet/22/11/24/Brevet.pdf', upload_to='Brevet/%y/%m/%d', verbose_name='Brevet'),
        ),
        migrations.AddField(
            model_name='demandeced',
            name='ChapitreLivre',
            field=models.FileField(default='ChapitreLivre/22/11/24/Brevet.pdf', upload_to='ChapitreLivre/%y/%m/%d', verbose_name='ChapitreLivre'),
        ),
        migrations.AddField(
            model_name='demandeced',
            name='Communication',
            field=models.FileField(default='Communication/22/11/24/Communication.pdf', upload_to='Communication/%y/%m/%d', verbose_name='Communication'),
        ),
        migrations.AddField(
            model_name='demandeced',
            name='CommunicationOrale',
            field=models.FileField(default='CommunicationOrale/22/11/24/CommunicationOrale.pdf', upload_to='CommunicationOrale/%y/%m/%d', verbose_name='CommunicationOrale'),
        ),
        migrations.AddField(
            model_name='demandeced',
            name='CommunicationPoster',
            field=models.ImageField(default='CommunicationPoster/22/11/24/CommunicationPoster.png', upload_to='CommunicationPoster/%y/%m/%d', verbose_name='CommunicationPoster'),
        ),
        migrations.AddField(
            model_name='demandeced',
            name='DemandeDirecteur',
            field=models.FileField(default='DemandeDirecteur/22/11/24/DemandeDirecteur.pdf', upload_to='DemandeDirecteur/%y/%m/%d', verbose_name='DemandeDirecteur'),
        ),
        migrations.AddField(
            model_name='demandeced',
            name='DemandeDoctorant',
            field=models.FileField(default='DemandeDoctorant/22/11/24/DemandeDoctorant.pdf', upload_to='DemandeDoctorant/%y/%m/%d', verbose_name='DemandeDoctorant'),
        ),
        migrations.AddField(
            model_name='demandeced',
            name='RapportDirecteur',
            field=models.FileField(default='RapportDirecteur/22/11/24/RapportDirecteur.pdf', upload_to='RapportDirecteur/%y/%m/%d', verbose_name='RapportDirecteur'),
        ),
        migrations.AddField(
            model_name='demandeced',
            name='These',
            field=models.FileField(default='These/22/11/24/These.pdf', upload_to='These/%y/%m/%d', verbose_name='These'),
        ),
        migrations.AddField(
            model_name='demandeced',
            name='lienPub1',
            field=models.CharField(default='', max_length=255, verbose_name='Lien Publication 1'),
        ),
        migrations.AddField(
            model_name='demandeced',
            name='lienPub2',
            field=models.CharField(default='', max_length=255, verbose_name='Lien Publication 2'),
        ),
        migrations.AddField(
            model_name='demandeced',
            name='lienPub3',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Lien Publication 3'),
        ),
        migrations.AddField(
            model_name='demandeced',
            name='lienPub4',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Lien Publication 4'),
        ),
    ]
