# Generated by Django 4.0.4 on 2023-02-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_demandeced_brevet_demandeced_chapitrelivre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeced',
            name='EmailExaminateur',
            field=models.CharField(default='', max_length=255, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='demandeced',
            name='EmailExaminateur2',
            field=models.CharField(default='', max_length=255, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='demandeced',
            name='EmailPresident',
            field=models.CharField(default='', max_length=255, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='demandeced',
            name='EmailRapporteur',
            field=models.CharField(default='', max_length=255, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='demandeced',
            name='EmailRapporteur2',
            field=models.CharField(default='', max_length=255, verbose_name='Email2'),
        ),
        migrations.AddField(
            model_name='demandeced',
            name='EmailRapporteur3',
            field=models.CharField(default='', max_length=255, verbose_name='Email3'),
        ),
        migrations.AddField(
            model_name='demandeced',
            name='EtablisementExaminateur',
            field=models.CharField(default='', max_length=255, verbose_name='Etablisement'),
        ),
        migrations.AddField(
            model_name='demandeced',
            name='EtablisementExaminateur2',
            field=models.CharField(default='', max_length=255, verbose_name='Etablisement Examinateur'),
        ),
        migrations.AddField(
            model_name='demandeced',
            name='EtablisementPresident',
            field=models.CharField(default='', max_length=255, verbose_name='Etablisement'),
        ),
        migrations.AddField(
            model_name='demandeced',
            name='EtablisementRapporteur',
            field=models.CharField(default='', max_length=255, verbose_name='Etablisement'),
        ),
        migrations.AddField(
            model_name='demandeced',
            name='EtablisementRapporteur2',
            field=models.CharField(default='', max_length=255, verbose_name='Etablisement2'),
        ),
        migrations.AddField(
            model_name='demandeced',
            name='EtablisementRapporteur3',
            field=models.CharField(default='', max_length=255, verbose_name='Etablisement3'),
        ),
        migrations.AddField(
            model_name='demandeced',
            name='NomExaminateur',
            field=models.CharField(default='', max_length=255, verbose_name='Nom Examinateur'),
        ),
        migrations.AddField(
            model_name='demandeced',
            name='NomPresident',
            field=models.CharField(default='', max_length=255, verbose_name='Nom Président'),
        ),
        migrations.AddField(
            model_name='demandeced',
            name='PrenomExaminateur',
            field=models.CharField(default='', max_length=255, verbose_name='Prenom Examinateur'),
        ),
        migrations.AddField(
            model_name='demandeced',
            name='PrenomExaminateur2',
            field=models.CharField(default='', max_length=255, verbose_name='Prenom Examinateur'),
        ),
        migrations.AddField(
            model_name='demandeced',
            name='PrenomPresident',
            field=models.CharField(default='', max_length=255, verbose_name='Prenom Président'),
        ),
        migrations.AddField(
            model_name='demandeced',
            name='PrenomRapporteur',
            field=models.CharField(default='', max_length=255, verbose_name='Prenom Rapporteur '),
        ),
        migrations.AddField(
            model_name='demandeced',
            name='PrenomRapporteur2',
            field=models.CharField(default='', max_length=255, verbose_name='Prenom Rapporteur2'),
        ),
        migrations.AddField(
            model_name='demandeced',
            name='TeleExaminateur',
            field=models.CharField(default='', max_length=255, verbose_name='Tele'),
        ),
        migrations.AddField(
            model_name='demandeced',
            name='TeleExaminateur2',
            field=models.CharField(default='', max_length=255, verbose_name='Tele'),
        ),
        migrations.AddField(
            model_name='demandeced',
            name='TelePresident',
            field=models.CharField(default='', max_length=255, verbose_name='Tele'),
        ),
        migrations.AddField(
            model_name='demandeced',
            name='TeleRapporteur',
            field=models.CharField(default='', max_length=255, verbose_name='Tele'),
        ),
        migrations.AddField(
            model_name='demandeced',
            name='TeleRapporteur2',
            field=models.CharField(default='', max_length=255, verbose_name='Tele2'),
        ),
        migrations.AddField(
            model_name='demandeced',
            name='TeleRapporteur3',
            field=models.CharField(default='', max_length=255, verbose_name='Tele3'),
        ),
    ]
