# Generated by Django 4.0.4 on 2023-02-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_demandeced_emailexaminateur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeced',
            name='NomExaminateur2',
            field=models.CharField(default='', max_length=255, verbose_name='Nom Examinateur2'),
        ),
        migrations.AddField(
            model_name='demandeced',
            name='NomRapporteur',
            field=models.CharField(default='', max_length=255, verbose_name='Nom Rapporteur1'),
        ),
        migrations.AddField(
            model_name='demandeced',
            name='NomRapporteur2',
            field=models.CharField(default='', max_length=255, verbose_name='Nom Rapporteur2'),
        ),
        migrations.AddField(
            model_name='demandeced',
            name='NomRapporteur3',
            field=models.CharField(default='', max_length=255, verbose_name='Nom Rapporteur3'),
        ),
        migrations.AddField(
            model_name='demandeced',
            name='PrenomRapporteur3',
            field=models.CharField(default='', max_length=255, verbose_name='Prenom Rapporteur3'),
        ),
        migrations.AlterField(
            model_name='demandeced',
            name='EmailExaminateur',
            field=models.CharField(default='', max_length=255, verbose_name='Email Examinateur'),
        ),
        migrations.AlterField(
            model_name='demandeced',
            name='EmailExaminateur2',
            field=models.CharField(default='', max_length=255, verbose_name='Email Examinateur2'),
        ),
        migrations.AlterField(
            model_name='demandeced',
            name='EmailPresident',
            field=models.CharField(default='', max_length=255, verbose_name='Email Président'),
        ),
        migrations.AlterField(
            model_name='demandeced',
            name='EmailRapporteur',
            field=models.CharField(default='', max_length=255, verbose_name='Email Rapporteur1'),
        ),
        migrations.AlterField(
            model_name='demandeced',
            name='EmailRapporteur2',
            field=models.CharField(default='', max_length=255, verbose_name='Email Rapporteur2'),
        ),
        migrations.AlterField(
            model_name='demandeced',
            name='EmailRapporteur3',
            field=models.CharField(default='', max_length=255, verbose_name='Email Rapporteurs3'),
        ),
        migrations.AlterField(
            model_name='demandeced',
            name='EtablisementExaminateur',
            field=models.CharField(default='', max_length=255, verbose_name='Etablissement'),
        ),
        migrations.AlterField(
            model_name='demandeced',
            name='EtablisementExaminateur2',
            field=models.CharField(default='', max_length=255, verbose_name='Etablissement Examinateur2'),
        ),
        migrations.AlterField(
            model_name='demandeced',
            name='EtablisementPresident',
            field=models.CharField(default='', max_length=255, verbose_name='Etablissement Président'),
        ),
        migrations.AlterField(
            model_name='demandeced',
            name='EtablisementRapporteur',
            field=models.CharField(default='', max_length=255, verbose_name='Etablisement Rapporteur1'),
        ),
        migrations.AlterField(
            model_name='demandeced',
            name='EtablisementRapporteur2',
            field=models.CharField(default='', max_length=255, verbose_name='Etablissement Rapporteur2'),
        ),
        migrations.AlterField(
            model_name='demandeced',
            name='EtablisementRapporteur3',
            field=models.CharField(default='', max_length=255, verbose_name='Etablissement Rapporteur3'),
        ),
        migrations.AlterField(
            model_name='demandeced',
            name='PrenomExaminateur2',
            field=models.CharField(default='', max_length=255, verbose_name='Prenom Examinateur2'),
        ),
        migrations.AlterField(
            model_name='demandeced',
            name='PrenomRapporteur',
            field=models.CharField(default='', max_length=255, verbose_name='Prenom Rapporteur1'),
        ),
        migrations.AlterField(
            model_name='demandeced',
            name='TeleExaminateur',
            field=models.CharField(default='', max_length=255, verbose_name='Tele Examinateur'),
        ),
        migrations.AlterField(
            model_name='demandeced',
            name='TeleExaminateur2',
            field=models.CharField(default='', max_length=255, verbose_name='Tele Examinateur2'),
        ),
        migrations.AlterField(
            model_name='demandeced',
            name='TelePresident',
            field=models.CharField(default='', max_length=255, verbose_name='Tele Président'),
        ),
        migrations.AlterField(
            model_name='demandeced',
            name='TeleRapporteur',
            field=models.CharField(default='', max_length=255, verbose_name='Tele Rapporteur1'),
        ),
        migrations.AlterField(
            model_name='demandeced',
            name='TeleRapporteur2',
            field=models.CharField(default='', max_length=255, verbose_name='Tele Rapporteur2'),
        ),
        migrations.AlterField(
            model_name='demandeced',
            name='TeleRapporteur3',
            field=models.CharField(default='', max_length=255, verbose_name='Tele Rapporteur3'),
        ),
    ]
