# Generated by Django 4.0.4 on 2023-02-20 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_remove_demandeced_intituleethese'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeced',
            name='DatePropose',
            field=models.DateField(blank=True, null=True, verbose_name="Proposition d'une date "),
        ),
    ]
